variable "vpc-name" {}
variable "az1" {}
variable "az2" {}
variable "pub1" {}
variable "pub2" {}
variable "prv1" {}
variable "prv2" {}
variable "igw" {}
variable "eip" {}
variable "nat" {}
variable "pub-rt" {}
variable "prv-rt" {}